### ISSUE TITLE
Architect frontend routes

### ISSUE THREAD

**Issue by draymond63** [uwblueprint/rowan-house#25]
## Summary
For developer ease in the future, we will want to create all the pages and routes. This will stop every PR that works on a new page from editing the common pages and prevent merge conflicts. This task is broken up into two goals: theoretical & implementation.

The general routes (as given by Tim) are:
- authentication (sign in/up)
- course management
- course editor
- user management

As you can see, we are only focusing on the admin side of things for now. Don't worry about routes for viewing content as a user. For more info, please see the [Admin User Flow](https://www.figma.com/file/KMYHraOHMmaf9n92wZsiCc/Admin-User-Flow?node-id=0%3A1) made by the designers.

## Goals
- [ ] Determine the routes (URLs) that will exist in the frontend
  - Pen & Paper (or Figma or anything)
  - Once a schema has been decided talk to Daniel / the team to confirm
- [ ] Implement dummy pages for all routes
  - If you think it's necessary, it could be good add some buttons to some pages to ensure the routes work properly

## Implementation
This code should only be written in the frontend. Course/lesson editing pages exist at dynamic URLs, because every course/lesson should have it's own link to go to edit it. There will inevitably be questions that we will have to clarify with design.

**Comment by Shrinjay** [comment]
Based off what we talked about on call:

## Additional Goal:
- [ ] Define names of components and subcomponents that compose pages.

As a recap, I suggested we expand the scope to include that so that this ticket saves a lot more dev time down the line with deciding how components fit together. 

Also, do you mind if I make the flowchart on a personal Miro account? Like it better for whiteboarding than Figma.
